api_hash: 6aff8a9bf1cce3db766e2ebfb9423520
api_id: 13259570
chat_id: fanchaclub
last_read_message_id: 0
ids_to_retry: []
media_types:
- audio
- photo
- video
- document
- voice
- video_note
file_formats:
  audio:
  - all
  document:
  - all
  video:
  - all

proxy:
  scheme: socks5
  hostname: 127.0.0.1
  port: 7890